name: Build Mihomo Rules

on:
  workflow_dispatch:

  push:
    paths:
      - "sources/**"
      - "scripts/**"
      - ".github/workflows/**"

  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4


    - name: Download Mihomo
      run: |
        wget -O mihomo.gz https://github.com/MetaCubeX/mihomo/releases/latest/download/mihomo-linux-amd64-v1.19.29.gz
        gunzip mihomo.gz
        chmod +x mihomo


    - name: Build
      run: |
        python3 scripts/build.py


    - name: Commit
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add ruleset

        git commit -m "Update mihomo rules" || exit 0

        git push
